package request

type Authentication struct {
	ThreeDS  *ThreeDS  `json:"3ds,omitempty"`
	ThreeDS2 *ThreeDS2 `json:"3ds2,omitempty"`
	Amount   string    `json:"amount,omitempty"`
}

type ThreeDS struct {
	ACSECI string `json:"acsEci,omitempty"`

	// The authentication token Included in subsequent transaction request messages and used by the card scheme to verify that the authentication occurred and the values provided are valid. The token should be used unaltered. For 3DS version 1, this field corresponds to the Cardholder Authentication Verification Value (CAVV) for Visa, the Accountholder Authentication Value (AAV) for MasterCard and JCB, or the American Express Verification Value (AEVV) for American Express.
	// For 3DS version 2, this field corresponds to the Authentication Value.
	AuthenticationToken string `json:"authenticationToken,omitempty"`

	// For 3DS version 1, this field corresponds to the XID. The XID is an identifier generated by the gateway on behalf of the merchant.
	// For 3DS version 2, this field corresponds to the identifier assigned by the scheme directory server.
	// This identifier should be used in subsequent operation requests unaltered.
	// An XID submitted in this field must be in base64 format.
	TransactionID string `json:"transactionId,omitempty"`
}

type ThreeDS2 struct {
	//  The version of the EMV 3-D Secure protocol used to perform 3-D Secure authentication, in the format specified by EMVCo.
	ProtocolVersion string `json:"protocolVersion,omitempty"`

	// A code indicating the reason for the transaction status returned in authentication.3ds2.transactionStatus.
	StatusReasonCode string `json:"statusReasonCode,omitempty"`

	// This is the value returned in the transaction status field from the issuer's Access Control Server (ACS). For example, Y, N, U, A, R
	TransactionStatus string `json:"transactionStatus,omitempty"`
}
